name:                haskell-db
version:             0.1.0.0
github:              "biskit1943/haskell-db"
license:             BSD3
author:              "Maximilian Konter"
maintainer:          "biskit1943@gmx.de"
copyright:           "2019 Maximilian Konter"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/biskit1943/haskell-db#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline
- bytestring
- utf8-string
- containers
- stm
- split
- hxt

library:
  source-dirs: src

executables:
  haskell-db-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-db

tests:
  haskell-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-db
